### ISSUE TITLE
Current Flux Helm release missing repository authentication options

### ISSUE THREAD

**Issue by timwebster9** [weaveworks/flux#1706] opened 2019-02-06 10:44 UTC
The docs [here](https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#authentication-for-helm-repos) say you can configure authentication for a Helm repository by mounting a volume:
```
      {{- if .Values.helmOperator.configureRepositories.enable }}
      - name: {{ .Values.helmOperator.configureRepositories.volumeName | quote }}
        secret:
          secretName: {{ .Values.helmOperator.configureRepositories.secretName | quote }}
      - name: {{ .Values.helmOperator.configureRepositories.cacheVolumeName | quote }}
        emptyDir: {}
      {{- end }}
```

however the latest published chart doesn't appear to include this functionality.  Opening up the template `helm-operator-deployment.yaml` from the 0.6.0 tarball you can see it's missing:

```
      volumes:
      {{- if .Values.ssh.known_hosts }}
      - name: sshdir
        configMap:
          name: {{ template "flux.fullname" . }}-ssh-config
          defaultMode: 0600
      {{- end }}
      - name: git-key
        secret:
          {{- if .Values.helmOperator.git.secretName }}
          secretName: {{ .Values.helmOperator.git.secretName }}
          {{- else if .Values.git.secretName }}
          secretName: {{ .Values.git.secretName }}
          {{- else }}
          secretName: {{ template "flux.fullname" . }}-git-deploy
          {{- end }}
          defaultMode: 0400
      {{- if .Values.helmOperator.tls.enable }}
      - name: helm-tls-certs
        secret:
          secretName: {{ .Values.helmOperator.tls.secretName }}
          defaultMode: 0400
      {{- if .Values.helmOperator.tls.verify }}
      - name: helm-tls-ca
        configMap:
          name: {{ template "flux.fullname" . }}-helm-tls-ca-config
          defaultMode: 0600
      {{- end }}
      {{- end }}
```

So not sure what's going on here?  Should we clone this repo and install the chart that way?  Or do you not publish charts when merging to master?  What do you recommend?

**Comment by hiddeco** [comment] 2019-02-06 22:20
Our (chart) releases are manual (except for nightly Docker builds of both the Flux daemon and the Helm operator). Building nightly releases of the chart [has been discussed in #flux](https://weave-community.slack.com/archives/C4U5ATZ9S/p1548769042126900) but before this is possible we [first need to move away from hosting the chart version in a `gh-pages` branch](https://weave-community.slack.com/archives/C4U5ATZ9S/p1548769220128000).

So, to answer your question: if you can (or do) not (want to) wait on something that is present in `master` but has not ended up in an official chart release yet, you need to manually extract it from `master` and install it that way.

**Comment by timwebster9** [comment] 2019-02-07 09:17
Sure no problem - I just cloned the repo and installed the chart that way.

I guess my only suggestion would be to mention this in the docs somewhere (maybe in [this section](https://github.com/weaveworks/flux/blob/master/site/helm-get-started.md)).  It's a bit confusing when things don't work as expected according to the docs.

**Comment by seanbocz** [comment] 2019-02-07 17:22
A new release was just made that has the changes. I updated the docs before the release was made.

**Comment by hiddeco** [comment] 2019-02-18 16:41
> It's a bit confusing when things don't work as expected according to the docs.

I agree and we are still figuring out how we should handle this (tracked in #1268), as the issue is broader than just the 'getting started' section I am opposed to adding a note to that section.

I am closing this as your question has been answered, suggestions about what we could do about `master` docs running ahead of releases are welcome in #1268.

**Closed by hiddeco** 2019-02-18 16:41 UTC
Labels: question
