### ISSUE TITLE
/api/history 500s on dev

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#637] opened 2017-07-05 14:59 UTC
E.g. `https://frontend.dev.weave.works/api/app/proud-wind-05/api/flux/v6/history?service=%3Call%3E&limit=20`

returns
 - status: 500
 - res: `fetching all history events: json: cannot unmarshal array into Go value of type policy.Set`

**Comment by foot** [comment] 2017-07-05 15:18
Oops happens w/ updatePolicy too:

`PATCH http://localhost:4047/api/app/proud-wind-05/api/flux/v6/policies?user=simon%40weave.works` -> `400 json: cannot unmarshal array into Go value of type policy.Set`

**Comment by sambooo** [comment] 2017-07-05 15:40
I'm not immediately able to reproduce this error, since visiting `https://frontend.dev.weave.works/api/app/proud-wind-05/api/flux/v6/history?service=%3Call%3E&limit=20` in my browser is working currently.

Any steps to reproduce much appreciated :)

**Comment by sambooo** [comment] 2017-07-05 15:42
Ah, increasing the limit to the point where older history items are stored (ie limit=100) reproduces the error. It just turns out the most recent 20 or so history entries are in the new format and unmarshal fine.

**Comment by squaremo** [comment] 2017-07-06 12:19
> Oops happens w/ updatePolicy too

This one is relatively easy to remedy: a recent PR changed the type of the values to be sent to UpdatePolicy. Instead of e.g.,

    {
      "olleh/helloworld": {
        "remove: ["locked"]
      }
    }

it will need to be in the structure

    {
      "olleh/helloworld: {
        "remove": {"locked": "true"}
      }
    }

This is to accommodate setting policies that are not binary, e..g, adding a tag filter, which would look like this:

    {
      "olleh/helloworld: {
        "add": {"tag.hello": "master-*"}
      }
    }

**Comment by squaremo** [comment] 2017-07-07 15:25
Fixed by #640

**Closed by squaremo** 2017-07-07 15:25 UTC
Labels: bug
