### ISSUE TITLE
Add helm diff functionality to fluxctl

### ISSUE THREAD

**Issue by michaelgeorgeattard** [weaveworks/flux#2133] opened 2019-06-06 14:40 UTC
I propose adding helm diff functionality to `fluxctl` to:

* Locally test out `HelmRelease` changes before committing to origin
* Show diffs in `Flux` `HelmRelease` repository pull requests before merging

Currently this functionality can be hacked by copying `values` portion of `HelmRelease` to a separate file and running `helm diff` plugin accordingly.

**Comment by hiddeco** [comment] 2019-06-06 17:37
Duplicate of #1864

**Closed by hiddeco** 2019-06-06 17:37 UTC
Labels: blocked-needs-validation, enhancement
