### ISSUE TITLE
401 after rolling out fluxd?

### ISSUE THREAD

**Issue by jml** [weaveworks/flux#346] opened 2017-01-09 10:03 UTC
As part of our daily rollout process, I rolled out fluxd & then fluxsvc using fluxctl.

After rolling out fluxd successfully...

```console
$ fluxctl release --all --update-image=quay.io/weaveworks/fluxd:master-44986a5
Submitting release job...
Release job submitted, ID c68ab31b-350f-550f-f880-7aa5bfc4b77f
Status: Complete.

Here's what happened:
 1) Queued.
 2) Calculating release actions.
 3) Release quay.io/weaveworks/fluxd:master-44986a5 to all services
 4) service default/kubernetes does not have images associated: empty selector
 5) service kube-system/scope-probe does not have images associated: no matching replication controllers or deployments
 6) Clone the config repo.
 7) Clone OK.
 8) Update 1 images(s) in the resource definition file for fluxy/fluxd: fluxd (quay.io/weaveworks/fluxd:master-e02dc33 -> quay.io/weaveworks/fluxd:master-44986a5).
 9) Update pod controller OK.
 10) Commit and push the config repo.
 11) Pushed commit: Release quay.io/weaveworks/fluxd:master-44986a5 to all services
 12) Release 1 service(s): fluxy/fluxd.
Took 15.775678s
```

I tried rolling out fluxsvc...

```console
$ fluxctl release --all --update-image=quay.io/weaveworks/fluxsvc:master-44986a5
Submitting release job...
Problem communicating with the service:  401 Unauthorized ()
Run 'fluxctl release --help' for usage.
```

Despite my credentials not changing. When I tried again immediately following, the deployment succeeded:

```console
$ fluxctl release --all --update-image=quay.io/weaveworks/fluxsvc:master-44986a5
Submitting release job...
Release job submitted, ID f94df3f5-ddce-6852-d3e4-95c1f77d102a
Status: Complete.

Here's what happened:
 1) Queued.
 2) Calculating release actions.
 3) Release quay.io/weaveworks/fluxsvc:master-44986a5 to all services
 4) service default/kubernetes does not have images associated: empty selector
 5) service kube-system/scope-probe does not have images associated: no matching replication controllers or deployments
 6) Clone the config repo.
 7) Clone OK.
 8) Update 1 images(s) in the resource definition file for fluxy/fluxsvc: fluxsvc (quay.io/weaveworks/fluxsvc:master-e02dc33 -> quay.io/weaveworks/fluxsvc:master-44986a5).
 9) Update pod controller OK.
 10) Commit and push the config repo.
 11) Pushed commit: Release quay.io/weaveworks/fluxsvc:master-44986a5 to all services
 12) Release 1 service(s): fluxy/fluxsvc.
Took 14.832377s
```

**Comment by paulbellamy** [comment] 2017-01-10 12:41
Seems unrelated to deploys. it's just intermittent on prod.

**Comment by philwinder** [comment] 2017-01-11 11:12
@jml I get a 401 from `fluxctl` when the `fluxd`/`fluxsvc` pod has failed to start.

**Comment by paulbellamy** [comment] 2017-01-11 11:32
This issue was specifically caused by #1055, so is fixed now. It is unclear what status "should" be returned by fluxctl when fluxd is not running. Probably no status at all, and just a better error message output. That is covered in: https://github.com/weaveworks/flux/issues/263

Closing this specific issue.

**Closed by paulbellamy** 2017-01-11 11:32 UTC
Labels: bug
