### ISSUE TITLE
Configure instructions not always displaying

### ISSUE THREAD

**Issue by BenHall** [weaveworks/flux#763] opened 2017-09-29 15:37 UTC
Within Weave Cloud, I feel like the kubectl command to configure Flux and a Git registry sometimes appears and not with other times.

When should the command box appear?

Example from within my account: 

![screenshot 2017-09-29 16 35 10](https://user-images.githubusercontent.com/82614/31023632-5d88d716-a534-11e7-8e34-c8ddc226dad2.png)

**Comment by BenHall** [comment] 2017-09-29 15:38
Likewise, after I've updated the config, I would expect to see the box appear

![screenshot 2017-09-29 16 38 00](https://user-images.githubusercontent.com/82614/31023693-93f2e170-a534-11e7-8379-cb7b87c2f162.png)

**Comment by squaremo** [comment] 2017-10-23 16:43
@BenHall It looks like you are seeing the config page for old versions of the flux agent. Our detection of what's connected can be a bit unreliable (in part because it relies on the agent being connected at that time; and, you know, complication and bugs ...).

> When should the command box appear?

It should always be shown on that page, if you have ever connected a (>=v1) flux agent. It is these days pretty difficult to run an old (<v1) flux agent.

Steps to reproduce gratefully pored over :)

**Comment by sambooo** [comment] 2018-03-23 23:06
Closing this as it is not a Flux issue, but a Weave Cloud issue.

**Closed by sambooo** 2018-03-23 23:06 UTC
