### ISSUE TITLE
fluxctl falsely fails when deploying fluxy

### ISSUE THREAD

**Issue by jml** [weaveworks/flux#186] opened 2016-10-05 11:25 UTC
`fluxctl` fails with an error when it is used to deploy fluxy:

```
Error: executing HTTP request: reading HTTP response: 503 Service Unavailable ({"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no endpoints available for service \"fluxy\"","reason":"ServiceUnavailable","code":503})
```

But of course, fluxy is running:

```
$ kubectl get --namespace fluxy po
NAME                     READY     STATUS    RESTARTS   AGE
fluxy-3190485323-xpk4p   1/1       Running   0          1m
```

And the new version has been deployed:

```
$ kubectl get -o json --namespace fluxy po | jq '.items[].status.containerStatuses[].image'
"quay.io/weaveworks/fluxy:master-06def3e"
```

Full log below:

```
$ fluxctl --url=http://localhost:8001/api/v1/proxy/namespaces/fluxy/services/fluxy release --all --update-image=quay.io/weaveworks/fluxy:master-06def3e
t=0 Submitting release job...
t=0 Release job submitted, ID 71daf431-1ab8-2574-7a99-73b9342510fb
t=1 Calculating release actions.
t=2 Calculating release actions.
t=3 Calculating release actions.
t=4 Calculating release actions.
t=5 Calculating release actions.
t=6 Calculating release actions.
t=7 Calculating release actions.
t=8 Calculating release actions.
t=9 Calculating release actions.
t=10 Calculating release actions.
t=11 Calculating release actions.
t=12 Calculating release actions.
t=13 Calculating release actions.
t=14 Update 1 images(s) in the resource definition file for fluxy/fluxy: fluxy (quay.io/weaveworks/fluxy:master-a9dd298 -> quay.io/weaveworks/fluxy:master-06def3e).
t=15 Update 1 images(s) in the resource definition file for fluxy/fluxy: fluxy (quay.io/weaveworks/fluxy:master-a9dd298 -> quay.io/weaveworks/fluxy:master-06def3e).
t=16 Update 1 images(s) in the resource definition file for fluxy/fluxy: fluxy (quay.io/weaveworks/fluxy:master-a9dd298 -> quay.io/weaveworks/fluxy:master-06def3e).
t=17 Update 1 images(s) in the resource definition file for fluxy/fluxy: fluxy (quay.io/weaveworks/fluxy:master-a9dd298 -> quay.io/weaveworks/fluxy:master-06def3e).
t=18 Update 1 images(s) in the resource definition file for fluxy/fluxy: fluxy (quay.io/weaveworks/fluxy:master-a9dd298 -> quay.io/weaveworks/fluxy:master-06def3e).
t=19 Update 1 images(s) in the resource definition file for fluxy/fluxy: fluxy (quay.io/weaveworks/fluxy:master-a9dd298 -> quay.io/weaveworks/fluxy:master-06def3e).
t=20 Update 1 images(s) in the resource definition file for fluxy/fluxy: fluxy (quay.io/weaveworks/fluxy:master-a9dd298 -> quay.io/weaveworks/fluxy:master-06def3e).
t=21 Commit and push the config repo.
t=22 Commit and push the config repo.
t=23 Commit and push the config repo.
t=24 Commit and push the config repo.
t=25 Release errored!
Error: executing HTTP request: reading HTTP response: 503 Service Unavailable ({"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no endpoints available for service \"fluxy\"","reason":"ServiceUnavailable","code":503})
```

**Comment by squaremo** [comment] 2016-11-24 13:24
These are the concrete problems:

 1. The client treats a "service unavailable" result as a failure, so it looks like the upgrade failed when it may have succeeded.
 2. Upgrading the image of the fluxsvc makes the service unavailable (see above), but also kills the worker thread that's running the upgrade itself, so it never completes. This means it never gets marked as complete, doesn't log a history entry, and doesn't send anything to Slack. (But, since it's a deployment, it does actually finish happening -- the service just doesn't see it)

Some measures we can take to help with 1):

 a. Make the client more resilient to service outages, at least when following the status of a release. A retry with back-off seems reasonable.
 b. In the running cluster, have more than one service pod running, so that there are fewer outages.

There is still 2.) -- worker threads are located in the service, potentially long-running, and can't upgrade themselves without being killed. It is really a specific case of this problem: doing a release is a long-running job, and terminating in the middle means it doesn't get finished. This can happen with any release -- it's just that upgrading the service is a guaranteed way of provoking it.

Ideally, we'd like to *always* be able to observe the completion of a release, even if the worker is killed in the middle. This suggests making jobs "recoverable"; i.e., if a worker fails, another can pick the job up.

(Another possibility is to declare a release complete once `kubectl apply -f deployment.yaml` is under way, which is not a bad 80% solution -- the problem is that this means the user doesn't know when a release is *really* complete, or indeed whether it was ultimately successful)

**Comment by squaremo** [comment] 2016-11-24 14:09
On this:

> This suggests making jobs "recoverable"; i.e., if a worker fails, another can pick the job up.

The two effects that a release job has are to push a commit to the config repo, and to apply a new config to the cluster. If the first happens, the second _should_ happen in short succession -- but if it doesn't, it can be corrected by the user, or picked up by another worker, provided the failure is visible.

The natural places from which to recover are, therefore:

 1. at any point up to the repository being pushed, the job can be restarted entirely;
 2. after the repository has been pushed, the platform should be told to regrade;
 3. after the platform has been told to regrade, it can be asked what happened.

3) wouldn't work at the minute, because workers block on regrade returning -- the platform protocol would have to change -- however it's the one that makes the most difference, because the middle of running the regrade is where failures tend to happen.

To be able to recover a job, claims on jobs must expire. The obvious way to do this is to look at the heartbeat, since that is maintained by the worker. If the heartbeat hasn't been updated (in X seconds), you can assume the claim is void, and claim the job for yourself.

**Comment by squaremo** [comment] 2016-11-25 14:18
Alternatively, we can just paper over this immediate problem by treating fluxsvc as a special case, and doing it async (i.e., applying the config then immediately returning). It will still be possible that `kubectl apply` kills the process before it writes an update to the database (or sends the Slack notification) though.

**Comment by jml** [comment] 2016-11-28 15:50
Tried this again & got a different error message:

```
$ fluxctl release --all --update-image quay.io/weaveworks/fluxsvc:master-6e41342
Submitting release job...
Release job submitted, ID 57b83065-e587-5761-d2ed-37aa45dd57c8
Status: error querying release.
Error: executing HTTP request: reading HTTP response: 502 Bad Gateway ()
```

**Comment by jml** [comment] 2016-11-28 15:51
But then tried again and it worked.

**Comment by squaremo** [comment] 2016-11-29 10:51
The minimal fix is:

 1. Get the client to deal with service outages by retrying (with backoff)
 2. Make the fluxsvc a special case in the releaser, for which it records the history and slack notification before sending the regrade message, and doesn't expect a reply (for now). If it comes as part of a bunch of regrades, separate it out and do it last.

This still means releases aren't recoverable -- restarting a service pod will lose any regrades underway -- but it _mostly_ fixes the spurious error we get on upgrading the service, I think.

**Comment by squaremo** [comment] 2016-11-30 13:56
#261 makes deploying specifically fluxsvc go a lot smoother. Since we have #181 for making fluxctl cope better with outages, and #256 to make releases properly recoverable, I'm closing this one.

**Closed by squaremo** 2016-11-30 13:56 UTC
