### ISSUE TITLE
Helm operator fails to parse git repo

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#1168] opened 2018-06-25 10:50 UTC
On master HEAD of as now:

```bash
$ kubectl get deployment -n weave weave-flux-helm-operator -oyaml|grep "image:"
        image: quay.io/weaveworks/helm-operator:master-ed0012d

$ kubectl logs -n weave deployment/weave-flux-helm-operator
ERROR: logging before flag.Parse: W0625 10:45:04.443528 \
  5 client_config.go:529] Neither --kubeconfig nor --master was specified. \
  Using the inClusterConfig.  This might not work.
ts=2018-06-25T10:45:04.494579694Z caller=helm.go:48 component=helm \
  info="Helm client set up"
ts=2018-06-25T10:45:04.494693935Z caller=main.go:174 component=helm-operator \
  error="Error parsing -git-url \"git@github.com:foot/flux-helm-test.git\": \
  parse git@github.com:foot/flux-helm-test.git: first path segment in URL cannot contain colon"
```

**Comment by squaremo** [comment] 2018-06-25 10:51
Duplicate of #1132.

**Comment by squaremo** [comment] 2018-06-25 10:52
Workaround: try using `ssh://git@github.com/foot/flux-helm-test` instead.

**Closed by squaremo** 2018-06-25 10:51 UTC
Labels: duplicate, helm
