### ISSUE TITLE
Namespace weaveworks has been disabled Error

### ISSUE THREAD

**Issue by ektakhandelwal** [weaveworks/flux#1953] opened 2019-04-17 20:06 UTC
When I do -  docker pull quay.io/weaveworks/flux

Then I am getting following Error - 

Get https://quay.io/v2/weaveworks/flux/manifests/latest: unknown: Namespace weaveworks has been disabled. Please contact a system administrator

**Comment by 2opremio** [comment] 2019-04-17 20:10
Duplicate of #1948

**Closed by 2opremio** 2019-04-17 20:10 UTC
