### ISSUE TITLE
Release not found

### ISSUE THREAD

**Issue by samheutmaker** [weaveworks/flux#2057] opened 2019-05-16 21:45 UTC
I'm having an issue getting Flux to read Helm charts from a private GitHub repository and apply changes to the cluster. I have Flux and the Helm Operator installed. I've created the deployment key, and Flux can read/write my repository.  My chart is custom, and contains 15 subcharts. Below is my HelmRelease:
```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sellout
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: sellout
  chart:
    git: git@github.com:sellout-tickets/SelloutOps
    ref: master
    path: charts/sellout
    values: 
      global: 
        # Image Config
        webAdminImageTag: 8adaff1
        webCheckoutImageTag: a9ed95d
        platformImageTag: a9ed95d
        # Environment Variables
        API_URL: https://graphql.sellout.cool
        ADMIN_UI_BASE_URL: https://app.sellout.cool
        # TLS Config
        tls: 
          email: sam@sellout.io
          domains: 
            admin: app.sellout.cool
            embed: embed.sellout.cool
            graphql: graphql.sellout.cool
```

Flux installs the sample applications just fine, but fails when trying to install the sellout chart. Below is the result of `kubectl describe hr sellout`:
```
Name:         sellout
Namespace:    default
Labels:       flux.weave.works/sync-gc-mark=sha256.jBy-XI76GHQT5sRtG08Tl4fMWyvooi-dMvBx3gFYstQ
Annotations:  flux.weave.works/automated: true
              flux.weave.works/sync-checksum: 4e62357b5df01e18f3afb71c10e7271e5567ab51
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"flux.weave.works/v1beta1","kind":"HelmRelease","metadata":{"annotations":{"flux.weave.works/automated":"true","flux.weave.w...
API Version:  flux.weave.works/v1beta1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2019-05-16T21:37:17Z
  Generation:          2
  Resource Version:    1685696
  Self Link:           /apis/flux.weave.works/v1beta1/namespaces/default/helmreleases/sellout
  UID:                 c6ecaad4-7822-11e9-b232-42010a800051
Spec:
  Chart:
    Git:   git@github.com:sellout-tickets/SelloutOps
    Path:  charts/sellout/
    Ref:   master
    Values:
      Global:
        ADMIN UI BASE URL:   https://app.sellout.cool
        API URL:             https://graphql.sellout.cool
        Platform Image Tag:  a9ed95d
        Tls:
          Domains:
            Admin:               app.sellout.cool
            Embed:               embed.sellout.cool
            Graphql:             graphql.sellout.cool
          Email:                 sam@sellout.io
        Web Admin Image Tag:     8adaff1
        Web Checkout Image Tag:  a9ed95d
  Release Name:                  sellout
Status:
  Conditions:
    Last Transition Time:  2019-05-16T21:37:41Z
    Message:               successfully cloned git repo
    Reason:                GitRepoCloned
    Status:                True
    Type:                  ChartFetched
    Last Transition Time:  2019-05-16T21:37:41Z
    Message:               rpc error: code = Unknown desc = release: "sellout" not found
    Reason:                HelmInstallFailed
    Status:                False
    Type:                  Released
  Release Name:            
  Release Status:          
Events:
  Type    Reason       Age              From           Message
  ----    ------       ----             ----           -------
  Normal  ChartSynced  1s (x3 over 9s)  helm-operator  Chart managed by HelmRelease processed
```

I've been fighting with this all day. Any help is greatly appreciated.

**Comment by hiddeco** [comment] 2019-05-21 09:30
Can you share the logs from the Helm operator from around the time it runs into the installation error?

**Comment by 2opremio** [comment] 2019-05-28 12:04
@samheutmaker Did you resolve this? Otherwise, can you share the logs? 

If it's still a problem, could you join the [#flux Slack channel channel](https://weave-community.slack.com/messages/flux/) so that we can pin-point it?

**Comment by hiddeco** [comment] 2019-05-31 11:29
@samheutmaker closing this to get it of our radar, if the problem surfaces again feel free to reopen the issue (or join `#flux` on Slack as mentioned above).

**Closed by hiddeco** 2019-05-31 11:29 UTC
Labels: blocked-needs-validation, bug

**Comment by johncf** [comment] 2019-10-24 02:26
I had the same issue. The problem was that my chart definition was bad (there was an undefined variable in it, due to which `flux-helm-operator` logs showed a `Chart release failed` error). Fixing the chart definition solved the issue.

**Comment by denysvitali** [comment] 2019-11-29 09:44
Can confirm what @johncf said: the error is due to an user error:
```
kubectl -n tiller logs -f deployments/tiller-deploy
```

In my case I was having a failure caused by a wrongly typed value. IMHO flux should show a more user-friendly error than `rpc error: code = Unknown desc = release: "RELEASE_NAME" not found`.  
I sugges something along the lines of `Deploy failed - Check Tiller logs`
