### ISSUE TITLE
git signature verification

### ISSUE THREAD

**Issue by jimmyjones2** [weaveworks/flux#1683] opened 2019-01-23 09:23 UTC
Git supports signing commits/tags with PGP. If flux could be configured with a set of allowed PGP keys, it would add another layer of defense.

As it stands, if someone can manage to commit (eg. insider, previous employee with unrevoked access, unpatched git sever, stolen domain creds etc) they can compromise the entire cluster. You'll have an audit log and hopefully someone should notice which is way better than the status quo, but this could further improve the already great security story of flux.

**Comment by hiddeco** [comment] 2019-01-23 09:43
Is it correct to assume this is a duplicate of #1394? (Which is being worked on in #1394).

**Closed** 2019-05-09 13:39 UTC
Labels: enhancement
