### ISSUE TITLE
Flux will not update environment when a new image is pushed

### ISSUE THREAD

**Issue by kevinm444** [weaveworks/flux#2172] opened 2019-06-19 23:49 UTC
**Describe the bug**
I am deploying Flux through Helm on to a Kubernetes cluster and Flux is not updating and re-deploying new images properly. When a new image is pushed onto the docker registry (Nexus Repository Manager), Flux sees this new image but does not update the existing container. I am also using semantic versioning to check the image tags (e.g imageExample:1, imageExample:2, etc)

Previously, this was working a few days ago and there was no problem at all. I wonder if it is the new patch causing this bug.

**Expected behavior**
I expect Flux to be able to update my existing container with the new image and since I am using semantic versioning, it should not check the timestamp at all.

**Logs**
ts=2019-06-19T17:15:25.807882143Z caller=images.go:107 component=sync-loop workload=dev:helmrelease/********** container=container repo=********** pattern=semver:* current=********** warning="image with zero created timestamp" current="********** (0001-01-01 00:00:00 +0000 UTC)" latest="********** (0001-01-01 00:00:00 +0000 UTC)" action="skip container"

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.13.0
- Helm Operator version: 0.92

**Comment by squaremo** [comment] 2019-06-20 10:46
I agree that if you're using semantic versioning, the timestamp shouldn't matter for deciding which image is more recent.

The reason for the check is slightly broader than that: a missing timestamp can indicate that the image tag in question doesn't have a (valid) manifest. That ought to be a distinct and detectable case, but -- I forget exactly why -- it's not.

Do you expect your images to have zero timestamps? Or is a secondary problem that fluxd isn't picking up their timestamps correctly?

**Comment by kevinm444** [comment] 2019-06-20 17:08
The docker image has the _Created_ field which has a valid timestamp, however the _LastTagTime_ in the Metadata object is set to 0 (as shown below).

"Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
}

I am wondering if this is the cause of the problem? Was Fluxd looking at the _Created_ field in the manifest before and after the patch it is looking at this instead?

**Comment by squaremo** [comment] 2019-07-04 15:26
fluxd doesn't look at the LastTagTime, no; just at the Created timestamp and the labels.

#2175 implements the expected behaviour; closing on that basis.

**Closed by squaremo** 2019-07-04 15:26 UTC
Labels: bug
