### ISSUE TITLE
Obscure kubectl error when releasing a service

### ISSUE THREAD

**Issue by mongrelion** [weaveworks/flux#553] opened 2017-04-28 11:57 UTC
I'm trying to release a new version of the helloworld example using a combination of `fluxctl` and my own installation of stand-alone Flux. However, at the moment of performing the release, Flux returns an error that's hard to comprehend.

I'm following [the official guide](https://github.com/weaveworks/flux/blob/67108e1e8d6fa8250c28f9b7b23e34a69a547e5b/site/using.md) on how to release a service and this is the error that I get:
```
$ fluxctl release --update-all-images --service default/helloworld
Submitting release job...
Release job submitted, ID ce1fe7a0-2f2e-d32b-7353-95fdf79cb5be
Status: Failed: default/helloworld: applying definition to default/helloworld: running kubectl: error: group map[batch:0xc8203a8ee0 componentconfig:0xc8203a8f50 extensions:0xc8203a8fc0 authentication.k8s.io:0xc8203a9180 :0xc8203a8d20 apps:0xc8203a8d90 autoscaling:0xc8203a8e70 rbac.authorization.k8s.io:0xc8203a90a0 federation:0xc8203a8cb0 authorization.k8s.io:0xc8203a8e00 policy:0xc8203a9030] is already registered


Here's as far as we got:
 1) Queued.
 2) Calculating updates for release.
 3) Cloning git repository.
 4) Finding defined services.
 5) Found service default/helloworld
 6) Found 1 services.
 7) Looking up images.
 8) Will update default/helloworld container helloworld: quay.io/weaveworks/helloworld:master-a000001 -> master-9a16ff945b9e
 9) Will update default/helloworld container sidecar: quay.io/weaveworks/sidecar:master-a000001 -> master-a000002
 10) Pushing changes.
 11) Applying changes.
 12) Failed: default/helloworld: applying definition to default/helloworld: running kubectl: error: group map[batch:0xc8203a8ee0 componentconfig:0xc8203a8f50 extensions:0xc8203a8fc0 authentication.k8s.io:0xc8203a9180 :0xc8203a8d20 apps:0xc8203a8d90 autoscaling:0xc8203a8e70 rbac.authorization.k8s.io:0xc8203a90a0 federation:0xc8203a8cb0 authorization.k8s.io:0xc8203a8e00 policy:0xc8203a9030] is already registered

Took 7.456812503s
== Error ==

Internal error: default/helloworld: applying definition to default/helloworld: running kubectl: error: group map[batch:0xc8203a8ee0 componentconfig:0xc8203a8f50 extensions:0xc8203a8fc0 authentication.k8s.io:0xc8203a9180 :0xc8203a8d20 apps:0xc8203a8d90 autoscaling:0xc8203a8e70 rbac.authorization.k8s.io:0xc8203a90a0 federation:0xc8203a8cb0 authorization.k8s.io:0xc8203a8e00 policy:0xc8203a9030] is already registered


We don't have a specific help message for the error above.

It would help us remedy this if you log an issue at

    https://github.com/weaveworks/flux/issues

saying what you were doing when you saw this, and quoting the message
at the top.
```

The service that I'm trying to deploy is the one mentioned in the guides, the [flux-example](https://github.com/weaveworks/flux-example) but using [my own fork](https://github.com/mongrelion/flux-example/) which has [one change](https://github.com/mongrelion/flux-example/commit/d472f2e48a75aa6477cbe7deab5bf202d7d05759) to the Kubernetes manifest so that the service port gets exposed in the cluster.

I have tried two different approaches for deploying Flux in my cluster:
1. Cloning the flux repository and deploying the manifests in the `deploy/standalone` [directory](https://github.com/weaveworks/flux/tree/67108e1e8d6fa8250c28f9b7b23e34a69a547e5b/deploy/standalone):
    ```
    $ kubectl create -f /path/to/flux/deploy/standalone/
    ```
2. Using the cloud.weave.works URL:
    ```
    $ kubectl apply -n kube-system -f "https://cloud.weave.works/k8s/v1.6/flux"
    ```

#### weave-flux-agent Pod
`agent`
```
2017-04-28T10:30:17.04740747Z ts=2017-04-28T10:30:17Z caller=release.go:85 component=platform method=Apply namespace=default service=helloworld result="error: group map[batch:0xc8203a8ee0 componentconfig:0xc8203a8f50 extensions:0xc8203a8fc0 authentication.k8s.io:0xc8203a9180 :0xc8203a8d20 apps:0xc8203a8d90 autoscaling:0xc8203a8e70 rbac.authorization.k8s.io:0xc8203a90a0 federation:0xc8203a8cb0 authorization.k8s.io:0xc8203a8e00 policy:0xc8203a9030] is already registered\n" took=645.961757ms
```

`server`
```
2017-04-28T10:30:17.048716574Z ts=2017-04-28T10:30:17Z caller=server.go:455 instanceID=<default-instance-id> method=Apply error="default/helloworld: applying definition to default/helloworld: running kubectl: error: group map[batch:0xc8203a8ee0 componentconfig:0xc8203a8f50 extensions:0xc8203a8fc0 authentication.k8s.io:0xc8203a9180 :0xc8203a8d20 apps:0xc8203a8d90 autoscaling:0xc8203a8e70 rbac.authorization.k8s.io:0xc8203a90a0 federation:0xc8203a8cb0 authorization.k8s.io:0xc8203a8e00 policy:0xc8203a9030] is already registered\n"
```

### Background Info
| What | Version |
|-------|-------|
| fluxctl | `0.2.0` |
| fluxsvc | `0.2.0` |
| fluxd | `0.2.0` |
| minikube | `v0.18.0` |
| kubectl | `v1.6.2` |
| kubernetes | `v1.6.0` |

I'm running the Kubernetes cluster with minikube @ 4096MB of memory. I've tried with both VirtualBox and VMWare Fusion providers and I still get the same error.

**Comment by errordeveloper** [comment] 2017-04-28 12:01
I wouldn't assume this can be to do with standalone mode, hence updated the title, unless you can prove that this is not the case when using hosted service...

**Comment by errordeveloper** [comment] 2017-04-28 12:03
Ok, I think it's be a very good idea to get latest version of Kubernetes, i.e. 1.6.2.

**Comment by squaremo** [comment] 2017-04-28 12:11
One theory: related to https://github.com/kubernetes/kubernetes/issues/35791

**Comment by mongrelion** [comment] 2017-05-02 08:38
@errordeveloper sorry for the late update. Minikube doesn't offer as of right now support for Kubernetes 1.6.0. Nothing higher than that. So I'm busy with setting up a Kubernetes cluster using `kubeadm` and Vagrant machines but I'm running into errors there as well.
I'll keep you posted.

**Comment by abuehrle** [comment] 2017-05-08 23:19
I see a similar rbac authentication error using the GUI in Weave Cloud: 

```
Release job submitted, ID d33547eb-7d38-82a9-b32b-6330a2d0f94d
Status: Failed: sock-shop/cart: applying definition to sock-shop/cart: running kubectl: error: group map[authentication.k8s.io:0xc8203c9420 :0xc8203c8fc0 apps:0xc8203c9030 autoscaling:0xc8203c9110 batch:0xc8203c9180 componentconfig:0xc8203c91f0 extensions:0xc8203c9260 federation:0xc8203c8f50 authorization.k8s.io:0xc8203c90a0 policy:0xc8203c92d0 rbac.authorization.k8s.io:0xc8203c9340] is already registered
```

**Comment by jpellizzari** [comment] 2017-05-18 05:07
Ran into this myself. Not sure if this is a dupe of https://github.com/kubernetes/kubernetes/issues/35791, but I found this as well: https://github.com/kubernetes/kubernetes/issues/39494

**Comment by squaremo** [comment] 2017-05-22 11:08
We released an image for fluxd that includes an much more recent `kubectl`, which gets past this particular problem. @jpellizzari or @mongrelion, can you confirm that fluxd is running, or at least not getting this error?

**Comment by squaremo** [comment] 2017-07-13 15:39
I believe we pinned this on the kubectl v kuubernetes API mismatch. As such: either use the fluxd:0.3.0 image, or try the new "git syncing" flux (not in a release yet).

**Closed by squaremo** 2017-07-13 15:39 UTC
