### ISSUE TITLE
GCR content-type errors

### ISSUE THREAD

**Issue by mithrandi** [weaveworks/flux#879] opened 2017-12-20 20:12 UTC
I'm seeing a lot of errors logged like this:

```
ts=2017-12-20T19:50:26.214459657Z caller=warming.go:148 component=warmer err="requesting manifests: getting remote manifest: Get https://gcr.io/v2/kubernetes-helm/tiller/manifests/v2.0.0: http: non-successful response (status=404 body=\"{\
\\"errors\\\":[{\\\"code\\\":\\\"MANIFEST_UNKNOWN\\\",\\\"message\\\":\\\"Manifest with tag 'v2.0.0' has media type 'application/vnd.docker.distribution.manifest.v1+prettyjws', but client accepts 'application/vnd.docker.distribution.manifest.v1+json'.\\\"}]}\")"
```

This is with Flux 1.1.0 as well as master. The images for the controller(s) in question show as "waiting for cache" forever, presumably due to this error.

**Comment by squaremo** [comment] 2017-12-22 10:57
Thanks for posting this issue @mithrandi. We were also seeing these log messages, as reported in #838. It was fixed in #851, which made its way to master pretty recently, and will be in the next release (soon!).

**Comment by squaremo** [comment] 2017-12-22 10:59
(closing as a duplicate of #838, but please do comment here, or file a further issue, if you still have problems that #851 is supposed to fix)

**Comment by mithrandi** [comment] 2017-12-22 11:00
Aha! It looks like I was running the `master` revision just before that was merged, upgrading does resolve the issue as expected.

**Closed by squaremo** 2017-12-22 10:59 UTC
Labels: bug, duplicate
